name: Dove Valley Swimming Club
favicon: null
layout_spectrum: 0.5624711364507675
typography_spectrum: 0.5590354020241648
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.30331046879291534
  lightness: 0.6338774911127985
  saturation: 0.6758163890335709
  rhythmicContrast: 0.060551645467057824
purpose: []
